using System;
using System.Collections.Generic;
using System.Text;

namespace DlcCreator.Utils
{
	// Token: 0x02000007 RID: 7
	public static class GenerateMetaData
	{
		// Token: 0x06000012 RID: 18 RVA: 0x000029AC File Offset: 0x00000BAC
		public static string GenerateContentXML(string DlcName, string Type)
		{
			string text = ":/%PLATFORM%/levels/gta5/";
			string text2 = "dlc_" + DlcName + ":/data/";
			string text3 = "dlc_" + DlcName + ":/%PLATFORM%/vehicles.rpf";
			string text4 = string.Concat(new string[] { "dlc_", DlcName, text, DlcName, ".rpf" });
			string text5 = string.Concat(new string[] { "dlc_", DlcName, text, DlcName, "_metadata.rpf" });
			string text6 = "";
			List<string> list = new List<string>();
			List<string> list2 = new List<string>();
			StringBuilder stringBuilder = new StringBuilder();
			stringBuilder.AppendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
			stringBuilder.AppendLine("<CDataFileMgr__ContentsOfDataFileXml>");
			stringBuilder.AppendLine("\t<disabledFiles />");
			stringBuilder.AppendLine("\t<includedXmlFiles />");
			stringBuilder.AppendLine("\t<includedDataFiles />");
			stringBuilder.AppendLine("\t<dataFiles>");
			bool flag = Type == "地图";
			if (flag)
			{
				stringBuilder.AppendLine("\t\t<Item>");
				stringBuilder.AppendLine("\t\t\t<filename>" + text4 + "</filename>");
				stringBuilder.AppendLine("\t\t\t<fileType>RPF_FILE</fileType>");
				stringBuilder.AppendLine("\t\t\t<overlay value=\"false\" />");
				stringBuilder.AppendLine("\t\t\t<disabled value=\"false\" />");
				stringBuilder.AppendLine("\t\t\t<persistent value=\"false\" />");
				stringBuilder.AppendLine("\t\t</Item>");
				stringBuilder.AppendLine("\t\t<Item>");
				stringBuilder.AppendLine("\t\t\t<filename>" + text5 + "</filename>");
				stringBuilder.AppendLine("\t\t\t<fileType>RPF_FILE</fileType>");
				stringBuilder.AppendLine("\t\t\t<overlay value=\"false\" />");
				stringBuilder.AppendLine("\t\t\t<disabled value=\"false\" />");
				stringBuilder.AppendLine("\t\t\t<persistent value=\"false\" />");
				stringBuilder.AppendLine("\t\t\t<contents>CONTENTS_DLC_MAP_DATA</contents>");
				stringBuilder.AppendLine("\t\t</Item>");
				text6 = "CCS_" + DlcName + "_NG_STREAMING_MAP";
				list2.Add("\t\t\t\t<Item>" + text4 + "</Item>");
				list2.Add("\t\t\t\t<Item>" + text5 + "</Item>");
				list.Add("\t\t\t<executionConditions>");
				list.Add("\t\t\t\t<activeChangesetConditions>");
				list.Add("\t\t\t\t</activeChangesetConditions>");
				list.Add("\t\t\t\t<genericConditions>$level=MO_JIM_L11</genericConditions>");
				list.Add("\t\t\t</executionConditions>");
			}
			else
			{
				bool flag2 = Type == "载具";
				if (flag2)
				{
					stringBuilder.AppendLine("\t\t<Item>");
					stringBuilder.AppendLine("\t\t\t<filename>" + text2 + "vehicles.meta</filename>");
					stringBuilder.AppendLine("\t\t\t<fileType>VEHICLE_METADATA_FILE</fileType>");
					stringBuilder.AppendLine("\t\t\t<overlay value=\"false\" />");
					stringBuilder.AppendLine("\t\t\t<disabled value=\"true\" />");
					stringBuilder.AppendLine("\t\t\t<persistent value=\"false\" />");
					stringBuilder.AppendLine("\t\t</Item>");
					stringBuilder.AppendLine("\t\t<Item>");
					stringBuilder.AppendLine("\t\t\t<filename>" + text2 + "carcols.meta</filename>");
					stringBuilder.AppendLine("\t\t\t<fileType>CARCOLS_FILE</fileType>");
					stringBuilder.AppendLine("\t\t\t<overlay value=\"false\" />");
					stringBuilder.AppendLine("\t\t\t<disabled value=\"true\" />");
					stringBuilder.AppendLine("\t\t\t<persistent value=\"false\" />");
					stringBuilder.AppendLine("\t\t</Item>");
					stringBuilder.AppendLine("\t\t<Item>");
					stringBuilder.AppendLine("\t\t\t<filename>" + text2 + "carvariations.meta</filename>");
					stringBuilder.AppendLine("\t\t\t<fileType>VEHICLE_VARIATION_FILE</fileType>");
					stringBuilder.AppendLine("\t\t\t<overlay value=\"false\" />");
					stringBuilder.AppendLine("\t\t\t<disabled value=\"true\" />");
					stringBuilder.AppendLine("\t\t\t<persistent value=\"false\" />");
					stringBuilder.AppendLine("\t\t</Item>");
					stringBuilder.AppendLine("\t\t<Item>");
					stringBuilder.AppendLine("\t\t\t<filename>" + text2 + "dlctext.meta</filename>");
					stringBuilder.AppendLine("\t\t\t<fileType>TEXTFILE_METAFILE</fileType>");
					stringBuilder.AppendLine("\t\t\t<overlay value=\"false\" />");
					stringBuilder.AppendLine("\t\t\t<disabled value=\"true\" />");
					stringBuilder.AppendLine("\t\t\t<persistent value=\"false\" />");
					stringBuilder.AppendLine("\t\t</Item>");
					stringBuilder.AppendLine("\t\t<Item>");
					stringBuilder.AppendLine("\t\t\t<filename>" + text2 + "handling.meta</filename>");
					stringBuilder.AppendLine("\t\t\t<fileType>HANDLING_FILE</fileType>");
					stringBuilder.AppendLine("\t\t\t<overlay value=\"false\" />");
					stringBuilder.AppendLine("\t\t\t<disabled value=\"true\" />");
					stringBuilder.AppendLine("\t\t\t<persistent value=\"false\" />");
					stringBuilder.AppendLine("\t\t</Item>");
					stringBuilder.AppendLine("\t\t<Item>");
					stringBuilder.AppendLine("\t\t\t<filename>" + text3 + "</filename>");
					stringBuilder.AppendLine("\t\t\t<fileType>RPF_FILE</fileType>");
					stringBuilder.AppendLine("\t\t\t<overlay value=\"false\" />");
					stringBuilder.AppendLine("\t\t\t<disabled value=\"true\" />");
					stringBuilder.AppendLine("\t\t\t<persistent value=\"true\" />");
					stringBuilder.AppendLine("\t\t</Item>");
					text6 = DlcName + "AUTOGEN";
					list2.Add("\t\t\t\t<Item>" + text2 + "handling.meta</Item>");
					list2.Add("\t\t\t\t<Item>" + text2 + "vehicles.meta</Item>");
					list2.Add("\t\t\t\t<Item>" + text2 + "carcols.meta</Item>");
					list2.Add("\t\t\t\t<Item>" + text2 + "carvariations.meta</Item>");
					list2.Add("\t\t\t\t<Item>" + text2 + "dlctext.meta</Item>");
					list2.Add("\t\t\t\t<Item>" + text3 + "</Item>");
					list.Add("\t\t\t<txdToLoad >");
					list.Add("\t\t\t<txdToUnLoad >");
					list.Add("\t\t\t<residentResources >");
					list.Add("\t\t\t<unregisterResources >");
				}
			}
			stringBuilder.AppendLine("\t</dataFiles>");
			stringBuilder.AppendLine("\t<contentChangeSets>");
			stringBuilder.AppendLine("\t\t<Item>");
			stringBuilder.AppendLine("\t\t\t<changeSetName>" + text6 + "</changeSetName>");
			stringBuilder.AppendLine("\t\t\t<filesToEnable>");
			for (int i = 0; i < list2.Count; i++)
			{
				stringBuilder.AppendLine(list2[i]);
			}
			stringBuilder.AppendLine("\t\t\t</filesToEnable>");
			for (int j = 0; j < list.Count; j++)
			{
				stringBuilder.AppendLine(list[j]);
			}
			stringBuilder.AppendLine("\t\t</Item>");
			stringBuilder.AppendLine("\t</contentChangeSets>");
			stringBuilder.AppendLine("\t<patchFiles />");
			stringBuilder.AppendLine("</CDataFileMgr__ContentsOfDataFileXml>");
			return stringBuilder.ToString();
		}

		// Token: 0x06000013 RID: 19 RVA: 0x0000305C File Offset: 0x0000125C
		public static string GenerateSetup2XML(string DlcName, string Type)
		{
			DateTime dateTime = default(DateTime);
			dateTime = DateTime.Now;
			StringBuilder stringBuilder = new StringBuilder();
			List<string> list = new List<string>();
			stringBuilder.AppendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
			stringBuilder.AppendLine("<SSetupData>");
			stringBuilder.AppendLine("\t<deviceName>dlc_" + DlcName + "</deviceName>");
			stringBuilder.AppendLine("\t<datFile>content.xml</datFile>");
			stringBuilder.AppendLine("\t<timeStamp>" + dateTime + "</timeStamp>");
			stringBuilder.AppendLine("\t<nameHash>" + DlcName + "</nameHash>");
			stringBuilder.AppendLine("\t<contentChangeSets />");
			stringBuilder.AppendLine("\t<contentChangeSetGroups>");
			bool flag = Type == "地图";
			if (flag)
			{
				stringBuilder.AppendLine("\t\t<Item>");
				stringBuilder.AppendLine("\t\t\t<NameHash>GROUP_EARLY_ON</NameHash>");
				stringBuilder.AppendLine("\t\t\t<ContentChangeSets>");
				stringBuilder.AppendLine("\t\t\t\t<Item>CCS_" + DlcName + "_NG_INIT</Item>");
				stringBuilder.AppendLine("\t\t\t</ContentChangeSets>");
				stringBuilder.AppendLine("\t\t</Item>");
				stringBuilder.AppendLine("\t\t<Item>");
				stringBuilder.AppendLine("\t\t\t<NameHash>GROUP_UPDATE_STREAMING</NameHash>");
				stringBuilder.AppendLine("\t\t\t<ContentChangeSets>");
				stringBuilder.AppendLine("\t\t\t\t<Item>CCS_" + DlcName + "_NG_STREAMING</Item>");
				stringBuilder.AppendLine("\t\t\t\t<Item>CCS_" + DlcName + "_NG_STREAMING_MAP</Item>");
				stringBuilder.AppendLine("\t\t\t</ContentChangeSets>");
				stringBuilder.AppendLine("\t\t</Item>");
				stringBuilder.AppendLine("\t\t<Item>");
				stringBuilder.AppendLine("\t\t\t<NameHash>GROUP_UPDATE_TEXT</NameHash>");
				stringBuilder.AppendLine("\t\t\t<ContentChangeSets>");
				stringBuilder.AppendLine("\t\t\t\t<Item>CCS_" + DlcName + "_NG_TEXT</Item>");
				stringBuilder.AppendLine("\t\t\t</ContentChangeSets>");
				stringBuilder.AppendLine("\t\t</Item>");
				list.Add("\t</contentChangeSetGroups>");
				list.Add("\t<startupScript />");
				list.Add("\t<scriptCallstackSize value=\"0\" />");
				list.Add("\t<type>EXTRACONTENT_LEVEL_PACK</type>");
				list.Add("\t<order value=\"2\" />");
				list.Add("\t<minorOrder value=\"0\" />");
				list.Add("\t<isLevelPack value=\"true\" />");
				list.Add("\t<dependencyPackHash />");
				list.Add("\t<requiredVersion />");
				list.Add("\t<subPackCount value=\"0\" />");
			}
			else
			{
				bool flag2 = Type == "载具";
				if (flag2)
				{
					stringBuilder.AppendLine("\t\t<Item>");
					stringBuilder.AppendLine("\t\t\t<NameHash>GROUP_STARTUP</NameHash>");
					stringBuilder.AppendLine("\t\t\t<ContentChangeSets>");
					stringBuilder.AppendLine("\t\t\t\t<Item>" + DlcName + "_AUTOGEN</Item>");
					stringBuilder.AppendLine("\t\t\t</ContentChangeSets>");
					stringBuilder.AppendLine("\t\t</Item>");
					list.Add("\t<type>EXTRACONTENT_COMPAT_PACK</type>");
					list.Add("\t<order value=\"9\" />");
				}
			}
			for (int i = 0; i < list.Count; i++)
			{
				stringBuilder.AppendLine(list[i]);
			}
			stringBuilder.AppendLine("</SSetupData>");
			return stringBuilder.ToString();
		}

		// Token: 0x06000014 RID: 20 RVA: 0x0000336C File Offset: 0x0000156C
		public static string GenerateDlcTextMETA(string DlcName)
		{
			StringBuilder stringBuilder = new StringBuilder();
			return stringBuilder.ToString();
		}

		// Token: 0x06000015 RID: 21 RVA: 0x0000338C File Offset: 0x0000158C
		public static string GenerateHandlingMETA(string DlcName)
		{
			StringBuilder stringBuilder = new StringBuilder();
			return stringBuilder.ToString();
		}

		// Token: 0x06000016 RID: 22 RVA: 0x000033AC File Offset: 0x000015AC
		public static string GenerateVehicleLayoutsMETA(string DlcName)
		{
			StringBuilder stringBuilder = new StringBuilder();
			return stringBuilder.ToString();
		}

		// Token: 0x06000017 RID: 23 RVA: 0x000033CC File Offset: 0x000015CC
		public static string GenerateVehiclesMETA(string DlcName)
		{
			StringBuilder stringBuilder = new StringBuilder();
			return stringBuilder.ToString();
		}

		// Token: 0x06000018 RID: 24 RVA: 0x000033EC File Offset: 0x000015EC
		public static string GenerateCarcolsMETA(string DlcName)
		{
			StringBuilder stringBuilder = new StringBuilder();
			stringBuilder.AppendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
			stringBuilder.AppendLine("<CVehicleModelInfoVarGlobal>");
			stringBuilder.AppendLine("<Kits>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<kitName>" + DlcName + "_modkit</kitName>");
			stringBuilder.AppendLine("<id value=\"1464\" />");
			stringBuilder.AppendLine("<kitType>MKT_SPECIAL</kitType>");
			stringBuilder.AppendLine("<visibleMods>");
			stringBuilder.AppendLine("</visibleMods>");
			stringBuilder.AppendLine("<linkMods />");
			stringBuilder.AppendLine("<statMods>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier />");
			stringBuilder.AppendLine("<modifier value=\"25\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"20\" />");
			stringBuilder.AppendLine("<type>VMT_ENGINE</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier />");
			stringBuilder.AppendLine("<modifier value=\"50\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"20\" />");
			stringBuilder.AppendLine("<type>VMT_ENGINE</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier />");
			stringBuilder.AppendLine("<modifier value=\"75\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"20\" />");
			stringBuilder.AppendLine("<type>VMT_ENGINE</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier />");
			stringBuilder.AppendLine("<modifier value=\"100\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"20\" />");
			stringBuilder.AppendLine("<type>VMT_ENGINE</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier />");
			stringBuilder.AppendLine("<modifier value=\"25\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"5\" />");
			stringBuilder.AppendLine("<type>VMT_BRAKES</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier />");
			stringBuilder.AppendLine("<modifier value=\"65\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"5\" />");
			stringBuilder.AppendLine("<type>VMT_BRAKES</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier />");
			stringBuilder.AppendLine("<modifier value=\"100\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"5\" />");
			stringBuilder.AppendLine("<type>VMT_BRAKES</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier />");
			stringBuilder.AppendLine("<modifier value=\"25\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"5\" />");
			stringBuilder.AppendLine("<type>VMT_GEARBOX</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier />");
			stringBuilder.AppendLine("<modifier value=\"50\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"5\" />");
			stringBuilder.AppendLine("<type>VMT_GEARBOX</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier />");
			stringBuilder.AppendLine("<modifier value=\"100\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"5\" />");
			stringBuilder.AppendLine("<type>VMT_GEARBOX</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier />");
			stringBuilder.AppendLine("<modifier value=\"20\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_ARMOUR</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier />");
			stringBuilder.AppendLine("<modifier value=\"40\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"10\" />");
			stringBuilder.AppendLine("<type>VMT_ARMOUR</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier />");
			stringBuilder.AppendLine("<modifier value=\"60\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"20\" />");
			stringBuilder.AppendLine("<type>VMT_ARMOUR</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier />");
			stringBuilder.AppendLine("<modifier value=\"80\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"30\" />");
			stringBuilder.AppendLine("<type>VMT_ARMOUR</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier />");
			stringBuilder.AppendLine("<modifier value=\"100\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"40\" />");
			stringBuilder.AppendLine("<type>VMT_ARMOUR</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>HORN_TRUCK</identifier>");
			stringBuilder.AppendLine("<modifier value=\"1766676233\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>HORN_COP</identifier>");
			stringBuilder.AppendLine("<modifier value=\"2904189469\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>HORN_CLOWN</identifier>");
			stringBuilder.AppendLine("<modifier value=\"2543206147\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>HORN_MUSICAL_1</identifier>");
			stringBuilder.AppendLine("<modifier value=\"1732399718\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>HORN_MUSICAL_2</identifier>");
			stringBuilder.AppendLine("<modifier value=\"2046162893\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>HORN_MUSICAL_3</identifier>");
			stringBuilder.AppendLine("<modifier value=\"2194999691\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>HORN_MUSICAL_4</identifier>");
			stringBuilder.AppendLine("<modifier value=\"2508304100\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>HORN_MUSICAL_5</identifier>");
			stringBuilder.AppendLine("<modifier value=\"3707223535\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>HORN_SAD_TROMBONE</identifier>");
			stringBuilder.AppendLine("<modifier value=\"632950117\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>MUSICAL_HORN_BUSINESS_1</identifier>");
			stringBuilder.AppendLine("<modifier value=\"3628534289\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>MUSICAL_HORN_BUSINESS_2</identifier>");
			stringBuilder.AppendLine("<modifier value=\"3892554122\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>MUSICAL_HORN_BUSINESS_3</identifier>");
			stringBuilder.AppendLine("<modifier value=\"4112892878\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>MUSICAL_HORN_BUSINESS_4</identifier>");
			stringBuilder.AppendLine("<modifier value=\"116877169\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>MUSICAL_HORN_BUSINESS_5</identifier>");
			stringBuilder.AppendLine("<modifier value=\"2684983719\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>MUSICAL_HORN_BUSINESS_6</identifier>");
			stringBuilder.AppendLine("<modifier value=\"2982690084\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>MUSICAL_HORN_BUSINESS_7</identifier>");
			stringBuilder.AppendLine("<modifier value=\"3203290992\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>DLC_BUSI2_C_MAJOR_NOTES_C0</identifier>");
			stringBuilder.AppendLine("<modifier value=\"771284519\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>DLC_BUSI2_C_MAJOR_NOTES_D0</identifier>");
			stringBuilder.AppendLine("<modifier value=\"2586621229\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>DLC_BUSI2_C_MAJOR_NOTES_E0</identifier>");
			stringBuilder.AppendLine("<modifier value=\"283386134\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>DLC_BUSI2_C_MAJOR_NOTES_F0</identifier>");
			stringBuilder.AppendLine("<modifier value=\"3884502400\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>DLC_BUSI2_C_MAJOR_NOTES_G0</identifier>");
			stringBuilder.AppendLine("<modifier value=\"265723083\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>DLC_BUSI2_C_MAJOR_NOTES_A0</identifier>");
			stringBuilder.AppendLine("<modifier value=\"1746883687\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>DLC_BUSI2_C_MAJOR_NOTES_B0</identifier>");
			stringBuilder.AppendLine("<modifier value=\"1919870950\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>DLC_BUSI2_C_MAJOR_NOTES_C1</identifier>");
			stringBuilder.AppendLine("<modifier value=\"1085277077\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>HIPSTER_HORN_1</identifier>");
			stringBuilder.AppendLine("<modifier value=\"444549672\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>HIPSTER_HORN_2</identifier>");
			stringBuilder.AppendLine("<modifier value=\"1603064898\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>HIPSTER_HORN_3</identifier>");
			stringBuilder.AppendLine("<modifier value=\"240366033\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>HIPSTER_HORN_4</identifier>");
			stringBuilder.AppendLine("<modifier value=\"960137118\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>INDEP_HORN_1</identifier>");
			stringBuilder.AppendLine("<modifier value=\"3572144790\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>INDEP_HORN_2</identifier>");
			stringBuilder.AppendLine("<modifier value=\"3801396714\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>INDEP_HORN_3</identifier>");
			stringBuilder.AppendLine("<modifier value=\"2843657151\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>INDEP_HORN_4</identifier>");
			stringBuilder.AppendLine("<modifier value=\"3341811489\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>LUXE_HORN_1</identifier>");
			stringBuilder.AppendLine("<modifier value=\"3199657341\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>LUXE_HORN_2</identifier>");
			stringBuilder.AppendLine("<modifier value=\"2900378064\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>LUXE_HORN_3</identifier>");
			stringBuilder.AppendLine("<modifier value=\"3956195248\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<!-- PREVIEW HORN - FOR MOD SHOP USE ONLY -->");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>LUXORY_HORN_1</identifier>");
			stringBuilder.AppendLine("<modifier value=\"676333254\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<!-- PREVIEW HORN - FOR MOD SHOP USE ONLY -->");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>LUXURY_HORN_2</identifier>");
			stringBuilder.AppendLine("<modifier value=\"2099578296\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<!-- PREVIEW HORN - FOR MOD SHOP USE ONLY -->");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier>LUXURY_HORN_3</identifier>");
			stringBuilder.AppendLine("<modifier value=\"1373384483\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_HORN</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier />");
			stringBuilder.AppendLine("<modifier value=\"1\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_SUSPENSION</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier />");
			stringBuilder.AppendLine("<modifier value=\"2\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_SUSPENSION</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier />");
			stringBuilder.AppendLine("<modifier value=\"3\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_SUSPENSION</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<identifier />");
			stringBuilder.AppendLine("<modifier value=\"4\" />");
			stringBuilder.AppendLine("<audioApply value=\"1.000000\" />");
			stringBuilder.AppendLine("<weight value=\"0\" />");
			stringBuilder.AppendLine("<type>VMT_SUSPENSION</type>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("</statMods>");
			stringBuilder.AppendLine("<slotNames />");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<slot>VMT_CHASSIS</slot>");
			stringBuilder.AppendLine("<name>TOP_CAGE</name>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("<liveryNames />");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("</Kits>");
			stringBuilder.AppendLine("<Lights>");
			stringBuilder.AppendLine("<Item>");
			stringBuilder.AppendLine("<id value=\"1464\" />");
			stringBuilder.AppendLine("<indicator>");
			stringBuilder.AppendLine("<intensity value=\"0.375000\" />");
			stringBuilder.AppendLine("<falloffMax value=\"2.500000\" />");
			stringBuilder.AppendLine("<falloffExponent value=\"8.000000\" />");
			stringBuilder.AppendLine("<innerConeAngle value=\"20.000000\" />");
			stringBuilder.AppendLine("<outerConeAngle value=\"50.000000\" />");
			stringBuilder.AppendLine("<emmissiveBoost value=\"true\" />");
			stringBuilder.AppendLine("<color value=\"0xfff2730c\" />");
			stringBuilder.AppendLine("</indicator>");
			stringBuilder.AppendLine("<rearIndicatorCorona>");
			stringBuilder.AppendLine("<size value=\"0.000000\" />");
			stringBuilder.AppendLine("<size_far value=\"0.000000\" />");
			stringBuilder.AppendLine("<intensity value=\"0.000000\" />");
			stringBuilder.AppendLine("<intensity_far value=\"0.000000\" />");
			stringBuilder.AppendLine("<color value=\"0x00000000\" />");
			stringBuilder.AppendLine("<numCoronas value=\"1\" />");
			stringBuilder.AppendLine("<distBetweenCoronas value=\"128\" />");
			stringBuilder.AppendLine("<distBetweenCoronas_far value=\"255\" />");
			stringBuilder.AppendLine("<xRotation value=\"0.000000\" />");
			stringBuilder.AppendLine("<yRotation value=\"0.000000\" />");
			stringBuilder.AppendLine("<zRotation value=\"0.000000\" />");
			stringBuilder.AppendLine("<zBias value=\"0.250000\" />");
			stringBuilder.AppendLine("<pullCoronaIn value=\"false\" />");
			stringBuilder.AppendLine("</rearIndicatorCorona>");
			stringBuilder.AppendLine("<frontIndicatorCorona>");
			stringBuilder.AppendLine("<size value=\"0.000000\" />");
			stringBuilder.AppendLine("<size_far value=\"0.000000\" />");
			stringBuilder.AppendLine("<intensity value=\"0.000000\" />");
			stringBuilder.AppendLine("<intensity_far value=\"0.000000\" />");
			stringBuilder.AppendLine("<color value=\"0x00000000\" />");
			stringBuilder.AppendLine("<numCoronas value=\"1\" />");
			stringBuilder.AppendLine("<distBetweenCoronas value=\"128\" />");
			stringBuilder.AppendLine("<distBetweenCoronas_far value=\"255\" />");
			stringBuilder.AppendLine("<xRotation value=\"0.000000\" />");
			stringBuilder.AppendLine("<yRotation value=\"0.000000\" />");
			stringBuilder.AppendLine("<zRotation value=\"0.000000\" />");
			stringBuilder.AppendLine("<zBias value=\"0.250000\" />");
			stringBuilder.AppendLine("<pullCoronaIn value=\"false\" />");
			stringBuilder.AppendLine("</frontIndicatorCorona>");
			stringBuilder.AppendLine("<tailLight>");
			stringBuilder.AppendLine("<intensity value=\"0.250000\" />");
			stringBuilder.AppendLine("<falloffMax value=\"4.000000\" />");
			stringBuilder.AppendLine("<falloffExponent value=\"16.000000\" />");
			stringBuilder.AppendLine("<innerConeAngle value=\"45.000000\" />");
			stringBuilder.AppendLine("<outerConeAngle value=\"90.000000\" />");
			stringBuilder.AppendLine("<emmissiveBoost value=\"false\" />");
			stringBuilder.AppendLine("<color value=\"0xFFFF0000\" />");
			stringBuilder.AppendLine("</tailLight>");
			stringBuilder.AppendLine("<tailLightCorona>");
			stringBuilder.AppendLine("<size value=\"0.000000\" />");
			stringBuilder.AppendLine("<size_far value=\"0.000000\" />");
			stringBuilder.AppendLine("<intensity value=\"5.000000\" />");
			stringBuilder.AppendLine("<intensity_far value=\"1.000000\" />");
			stringBuilder.AppendLine("<color value=\"0xFFFF0F05\" />");
			stringBuilder.AppendLine("<numCoronas value=\"0\" />");
			stringBuilder.AppendLine("<distBetweenCoronas value=\"1\" />");
			stringBuilder.AppendLine("<distBetweenCoronas_far value=\"56\" />");
			stringBuilder.AppendLine("<xRotation value=\"0.000000\" />");
			stringBuilder.AppendLine("<yRotation value=\"1.747000\" />");
			stringBuilder.AppendLine("<zRotation value=\"5.906000\" />");
			stringBuilder.AppendLine("<zBias value=\"0.250000\" />");
			stringBuilder.AppendLine("<pullCoronaIn value=\"false\" />");
			stringBuilder.AppendLine("</tailLightCorona>");
			stringBuilder.AppendLine("<tailLightMiddleCorona>");
			stringBuilder.AppendLine("<size value=\"0.000000\" />");
			stringBuilder.AppendLine("<size_far value=\"0.000000\" />");
			stringBuilder.AppendLine("<intensity value=\"0.000000\" />");
			stringBuilder.AppendLine("<intensity_far value=\"0.000000\" />");
			stringBuilder.AppendLine("<color value=\"0x00000000\" />");
			stringBuilder.AppendLine("<numCoronas value=\"0\" />");
			stringBuilder.AppendLine("<distBetweenCoronas value=\"128\" />");
			stringBuilder.AppendLine("<distBetweenCoronas_far value=\"255\" />");
			stringBuilder.AppendLine("<xRotation value=\"0.000000\" />");
			stringBuilder.AppendLine("<yRotation value=\"0.000000\" />");
			stringBuilder.AppendLine("<zRotation value=\"0.000000\" />");
			stringBuilder.AppendLine("<zBias value=\"0.250000\" />");
			stringBuilder.AppendLine("<pullCoronaIn value=\"false\" />");
			stringBuilder.AppendLine("</tailLightMiddleCorona>");
			stringBuilder.AppendLine("<headLight>");
			stringBuilder.AppendLine("<intensity value=\"0.800000\" />");
			stringBuilder.AppendLine("<falloffMax value=\"30.000000\" />");
			stringBuilder.AppendLine("<falloffExponent value=\"16.000000\" />");
			stringBuilder.AppendLine("<innerConeAngle value=\"0.000000\" />");
			stringBuilder.AppendLine("<outerConeAngle value=\"60.209999\" />");
			stringBuilder.AppendLine("<emmissiveBoost value=\"false\" />");
			stringBuilder.AppendLine("<color value=\"0xFF7FA7E3\" />");
			stringBuilder.AppendLine("<textureName>VehicleLight_car_standardmodern</textureName>");
			stringBuilder.AppendLine("<mirrorTexture value=\"false\" />");
			stringBuilder.AppendLine("</headLight>");
			stringBuilder.AppendLine("<headLightCorona>");
			stringBuilder.AppendLine("<size value=\"0.100000\" />");
			stringBuilder.AppendLine("<size_far value=\"0.100000\" />");
			stringBuilder.AppendLine("<intensity value=\"2.000000\" />");
			stringBuilder.AppendLine("<intensity_far value=\"1.000000\" />");
			stringBuilder.AppendLine("<color value=\"0xFFd1fbff\" />");
			stringBuilder.AppendLine("<numCoronas value=\"1\" />");
			stringBuilder.AppendLine("<distBetweenCoronas value=\"128\" />");
			stringBuilder.AppendLine("<distBetweenCoronas_far value=\"255\" />");
			stringBuilder.AppendLine("<xRotation value=\"0.000000\" />");
			stringBuilder.AppendLine("<yRotation value=\"0.000000\" />");
			stringBuilder.AppendLine("<zRotation value=\"0.000000\" />");
			stringBuilder.AppendLine("<zBias value=\"0.250000\" />");
			stringBuilder.AppendLine("<pullCoronaIn value=\"false\" />");
			stringBuilder.AppendLine("</headLightCorona>");
			stringBuilder.AppendLine("<reversingLight>");
			stringBuilder.AppendLine("<intensity value=\"0.030000\" />");
			stringBuilder.AppendLine("<falloffMax value=\"2.000000\" />");
			stringBuilder.AppendLine("<falloffExponent value=\"32.000000\" />");
			stringBuilder.AppendLine("<innerConeAngle value=\"45.000000\" />");
			stringBuilder.AppendLine("<outerConeAngle value=\"90.000000\" />");
			stringBuilder.AppendLine("<emmissiveBoost value=\"false\" />");
			stringBuilder.AppendLine("<color value=\"0xFFFFFFFF\" />");
			stringBuilder.AppendLine("</reversingLight>");
			stringBuilder.AppendLine("<reversingLightCorona>");
			stringBuilder.AppendLine("<size value=\"0.000000\" />");
			stringBuilder.AppendLine("<size_far value=\"0.000000\" />");
			stringBuilder.AppendLine("<intensity value=\"1.500000\" />");
			stringBuilder.AppendLine("<intensity_far value=\"1.000000\" />");
			stringBuilder.AppendLine("<color value=\"0x00F7F7F7\" />");
			stringBuilder.AppendLine("<numCoronas value=\"0\" />");
			stringBuilder.AppendLine("<distBetweenCoronas value=\"128\" />");
			stringBuilder.AppendLine("<distBetweenCoronas_far value=\"255\" />");
			stringBuilder.AppendLine("<xRotation value=\"0.000000\" />");
			stringBuilder.AppendLine("<yRotation value=\"0.000000\" />");
			stringBuilder.AppendLine("<zRotation value=\"0.000000\" />");
			stringBuilder.AppendLine("<zBias value=\"0.250000\" />");
			stringBuilder.AppendLine("<pullCoronaIn value=\"false\" />");
			stringBuilder.AppendLine("</reversingLightCorona>");
			stringBuilder.AppendLine("<name>as7</name>");
			stringBuilder.AppendLine("</Item>");
			stringBuilder.AppendLine("");
			stringBuilder.AppendLine("</Lights>");
			stringBuilder.AppendLine("</CVehicleModelInfoVarGlobal>");
			return stringBuilder.ToString();
		}
	}
}
